"""Generates Python TypedDict definitions for project-specific attributes.

This script fetches the custom attribute schema for a given project
from a server API and generates a TypedDict class definition that can be
that be used for type hinting in Python code.

Usage:
    Call it with the project name, server url and api key as arguments.
    Redirect the output to a .py file to save the generated types.

    Then in your code, import the generated types for use and cast
    dictionaries representing project attributes::

        from project_123_types import Project123Attributes

        attrs = cast(Project123Attributes, raw_attrs)

"""
import argparse
import sys
from typing import Any, Dict, List

import requests


def map_server_type_to_python(server_type: str) -> str:
    """Converts server-side type names to Python type hints.

    This might not be needed as server is using python too.

    Args:
        server_type (str): The type name as defined by the server.

    Returns:
        str: Corresponding Python type hint as a string.

    """
    # Customize this based on your server's type system
    type_map = {
        "string": "str",
        "integer": "int",
        "number": "float",  # or Union[int, float]
        "boolean": "bool",
        "date": "str",     # or datetime.date
    }
    # Return the mapped type, or 'Any' as a fallback
    return type_map.get(server_type, "Any")


def _mock_get_schema_for_project(
        project_name: str,
        server_url: str,
        api_key: str) -> List[Dict[str, Any]]:
    """Mocks a call to the server's 'get schema' endpoint.

    In reality, this would be an HTTP call. This endpoint isn't implemented
    yet, so we mock it here for demonstration purposes.

    Args:
        project_name (str): The project ID to fetch schema for.
        server_url (str): The server URL.
        api_key (str): API key for authentication.

    Returns:
        List[Dict[str, Any]]: The schema definition for the project.

    Raises:
        ValueError: If the project is not found.

    """
    print(  # noqa: T201
        f"INFO: Fetching schema for project {project_name}...",
        file=sys.stderr
    )

    session = requests.Session()
    session.headers.update({"x-api-key": api_key})
    _host = server_url

    if project_name == "project_123":
        return [
            {"name": "team_lead", "type": "string", "is_required": True},
            {"name": "budget", "type": "integer", "is_required": True},
            {"name": "is_internal", "type": "boolean", "is_required": False},
        ]
    msg = (
        f"Schema for project {project_name} not found."
        "This is a mock function; implement actual server call."
    )
    raise ValueError(msg)


def generate_typed_dict(
        project_name: str, schema: List[Dict[str, Any]]) -> str:
    """Generates the Python code for a TypedDict from the schema.

    Args:
        project_name (str): The name of the project.
        schema (List[Dict[str, Any]]): The schema definition for the project.

    Returns:
        str: The generated Python code as a string.
    """
    # Create a dynamic class name
    class_name = f"Project{project_name}Attributes"

    lines = [
        "# This file is auto-generated by generate_project_types.py",
        "# Do not edit this file manually.",
        "from typing import TypedDict, Optional",
        "",
        "",
        f"class {class_name}(TypedDict):",
        f'    """Type definition for Project {project_name}\'s custom attributes."""'  # noqa: E501
    ]

    if not schema:
        lines.append("    pass  # No custom attributes found")
        return "\n".join(lines)

    for attr in schema:
        name = attr.get("name")
        if not name:
            continue

        py_type = map_server_type_to_python(attr.get("type", "any"))

        # Handle optional vs. required fields
        if attr.get("is_required", False):
            lines.append(f"    {name}: {py_type}")
        else:
            # If not required, it might be missing from the dict
            # We make it Optional[...], which implies it can be missing.
            lines.append(f"    {name}: Optional[{py_type}]")

    return "\n".join(lines)


def main() -> None:
    """Main function to parse arguments and generate the TypedDict."""
    parser = argparse.ArgumentParser(
        description="Generate a TypedDict for a specific project's attributes."
    )
    parser.add_argument(
        "--project-code",
        type=int,
        required=True,
        help="The  name of the project to fetch schema for."
    )
    parser.add_argument(
        "--server-url",
        type=str,
        required=True,
        help="The URL of the server to fetch schema from."
    )
    parser.add_argument(
        "--api-key",
        type=str,
        required=True,
        help="API key for authenticating with the server."
    )

    args = parser.parse_args()


    session = requests.Session()
    session.headers.update({"x-api-key": args.api_key})

    try:
        # 1. Fetch the schema from the server
        schema = _mock_get_schema_for_project(
            args.project_name, args.server_url, args.api_key)

        # 2. Generate the TypedDict code
        code_string = generate_typed_dict(args.project_id, schema)

        # 3. Print the code to standard output
        print(code_string)  # noqa: T201

        print(  # noqa: T201
            "\n# INFO: Successfully generated types "
            f"for project {args.project_id}", file=sys.stderr)

    except Exception as e:  # noqa: BLE001
        print(f"Error: {e}", file=sys.stderr)  # noqa: T201
        sys.exit(1)


if __name__ == "__main__":
    main()
